### ISSUE TITLE
Edit publisher profile information

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#71] opened 2017-01-24 09:37 UTC
We need to provision the owner of the publisher to edit the publisher information.

implementation:
TODO

**Comment by rufuspollock** [comment] 2017-02-11 23:55
INVALID (possibly DUPLICATE of dpr-api). Not an issue for this repo (and not well-defined either).

**Closed as completed by rufuspollock** 2017-02-11 23:55 UTC
Labels: invalid
